### ISSUE TITLE
Event not sent

### ISSUE THREAD

**Issue by EscapeArtist** [hadilq/LiveEvent#11]
Hi there.
I'm sorry if this is vague but unfortunately I don't have much time to spend on this at this stage.
Anyway, I swapped my SingleLiveEvent class taken from the one on the google repo for yours since I needed the same functionality but with multiple observers.
All I did is a direct copy paste into the SingleLiveEvent class with your code in, and the very first event I use in the class ( it's on the main activity to decie whther to go to the login screen or Home ) never fired at all, so the app just hangs there.
I've left the exact same code as from SingleLiveEvent, only swapped out the code in the class, and it doesn't work.
I don't know if there's something obvious I'm missing...

**Comment by hadilq** [comment]
Thank you for your feedback.
I added some tests [here](https://github.com/hadilq/LiveEvent/pull/12) to check your claim, but they work as expected! Would you provide a test case? Thanks.

**Comment by hadilq** [comment]
Close due to inactivity.
