### ISSUE TITLE
LiveEvent and configuration changes

### ISSUE THREAD

**Issue by Entreco** [hadilq/LiveEvent#18]
I was under the impression that using LiveEvent, we would be able to use these events to trigger dialogs in a Fragment. E.g.

```
class MyFragment : Fragment(){
    override fun onCreateView(inflater: LayoutInflater,
                              container: ViewGroup?,
                              savedInstanceState: Bundle?): View? {

        val binding = // inflate view using Databinding
        binding.viewModel = // some viewModel
        viewModel.events().observe(viewLifecycleOwner, Observer { event ->
                showDialog(event)
        })
        return binding.root
    }
}
```

This is the ViewModel:
```
class MyViewModel : ViewModel(){
    private val events = MutableLiveData<DialogEvent>()
    fun events(): LiveData<DialogEvent> = events.toSingleEvent()

    fun onClick() = events.postValue(DialogEvent)
}

object DialogEvent
```

So, whenever I click a button, a dialog is shown.
However, when I rotate the screen, the dialog is shown again.
This makes sense, because on orientation change, the observer is removed, added again, and will receive the latest value...

Am I wrong that `LiveEvent` can be used in these scenario's?
Or am I missing something obvious?

**Comment by tobikster** [comment]
I think you should change the `events()` method in you ViewModel to property:

```
private val _events = MutableLiveData<DialogEvent>()
val events: LiveData<DialogEvent> = _events.toSingleEvent()
```

In the current implementation, every time you observe the event LiveData, the new `LiveEvent` is created, so the value wii be emitted again.

**Comment by hadilq** [comment]
As @tobikster explained correctly, the lifecycle of LiveEvent and the ViewModel must be the same, which means you must create a LiveEvent, or a LiveData, once per a ViewModel instance.
