### ISSUE TITLE
observeForever is not implemented

### ISSUE THREAD

**Issue by matsujun** [hadilq/LiveEvent#21]
```
    @MainThread
    override fun observeForever(observer: Observer<in T>) {
        val wrapper = ObserverWrapper(observer)
        observers.add(wrapper)
        super.observeForever(wrapper)
    }
```
is not implemented.

So LiveEvent is not possible to use source of MediatorLiveData.
(MediatorLiveData uses observeForever)

**Comment by hadilq** [comment]
Thanks for your contribution. Merge the https://github.com/hadilq/LiveEvent/pull/22 PR to solve the problem.
