### ISSUE TITLE
lib/src/../strings.xml is unused

### ISSUE THREAD

**Issue by vibin** [hadilq/LiveEvent#25]
Just a small nit here: https://github.com/hadilq/LiveEvent/blob/f47ac07a3fa6a7cf2af4e956416cc65032b29d56/lib/src/main/res/values/strings.xml can be deleted as it has just one string called `app_name` which is unused.

**Comment by hadilq** [comment]
Makes sense. Thank you, I removed it. https://github.com/hadilq/LiveEvent/pull/26

**Comment by vibin** [comment]
🙏
