### ISSUE TITLE
Make inheritance possible

### ISSUE THREAD

**Issue by FelipeRRM** [hadilq/LiveEvent#30]
Defining the class as `open` would allow inheritance, which is something that is not possible currently. For debugging reasons I am overriding the `setValue` method and adding logging there, something which is not possible with this implementation. I know I can easily log this elsewhere but more substantial changes would suffer from this.

**Comment by hadilq** [comment]
Thank you @FelipeRRM for your contribution. See 027ac57. If you need it so much I can release it. Just tell me ;)
