### ISSUE TITLE
Please add variant with check newValue and oldValue

### ISSUE THREAD

**Issue by JajaComp** [hadilq/LiveEvent#33]
If oldValue == newValue then ignore this. I need it for ClickEvent for to avoid of double tap problem with navigation.

**Comment by JajaComp** [comment]
oldValue you can reset in onInactive method

**Comment by hadilq** [comment]
Thank you @JajaComp for your contribution. I advise you to use `RxJava` or `Coroutines` to solve your distinction problem, then you can use my libraries https://github.com/hadilq/RxLifecycleHandler/ or https://github.com/hadilq/CoroutineLifecycleHandler/ to make your stream lifecycle aware.
