### ISSUE TITLE
[Feature Request] Optional behavior like Jose Alcerreca's EventWrapper class

### ISSUE THREAD

**Issue by TurKurT656** [hadilq/LiveEvent#35]
Its great now that we can add multiple observers to the `LiveEvent` object, But in most cases we want to act as we added a single observer. For example imagine that we accidentally added observer in `onViewCreated` of the fragment and we did not removed the observer. So after going to another fragment and getting back actions will be called twice (Or there can be another similar cases). I think it is good to have such a `SingleLiveEvent` class that only delivers data for the first observer in such cases.

Thanks

**Comment by hadilq** [comment]
Thank you @TurKurT656 The logic behind your argument is "we accidentally added observer" which is not acceptable IMHO. A simple find usage in IDEA would solve that problem. Also what would be the logic of `SingleLiveEvent`? Does it emit to the first observed observer or in case of adding new oberver it would detached the previously added ones, so it just emit to the last observed observer? Please if you answer it clarify why it's your choice. Thanks.

**Comment by TurKurT656** [comment]
yes this makes sense
