### ISSUE TITLE
implement postValue

### ISSUE THREAD

**Issue by baruchn** [hadilq/LiveEvent#41]
One of the most common usages of LiveData from a ViewModel is through the `postValue` method which doesn't seem to be implemented.

**Comment by hadilq** [comment]
Thanks @baruchn for your suggestion, but the `postValue` method is implemented by `LiveData` itself and `LiveEvent` extends it, which means you can call it. I have to mention that the `postValue` will call the `setValue` under the hood where we override it in `LiveEvent`, so if by this suggestion you mean by calling `postValue` there will be a bug, please specify that bug. Thanks!
